name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  ## What’s Changed
  $CHANGES
categories:
  - title: "🐞 Bug fixes"
    labels:
      - "bug"
  - title: "🔧 Dependency updates"
    labels:
      - "dependencies"
  - title: "🧹 Chores"
    labels:
      - "chore"
version-resolver:
  minor:
    labels:
      - 'breaking'
  default: patch
