platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: "lts-alpine"

inputs:
  - name: bento

params:
  CHROMATIC_PROJECT_TOKEN: ((chromatic-project-token))
  CHROMATIC_OPTIONS:

run:
  dir: bento
  path: ash
  args:
    - -ce
    - |
      corepack enable

      apk add --no-progress git

      # The pull request resource works by rebasing the PR branch on top of the target branch, which
      # will confuse Chromatic. We fix this by manually setting the metadata stored by the resource.
      # This is only needed on PRs, hence the check below.
      if [ -f .git/resource/head_sha ] && [ -f .git/resource/head_name ]; then
        export CHROMATIC_BRANCH=$(cat .git/resource/head_name)
        export CHROMATIC_SHA=$(cat .git/resource/head_sha)
      fi

      CHROMATIC_OPTIONS="--ci --exit-zero-on-changes --exit-once-uploaded ${CHROMATIC_OPTIONS}"
      pnpm chromatic
