platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: "lts-alpine"

inputs:
  - name: bento

outputs:
  - name: bento

caches:
  - path: bento/.pnpm-store

params:
  COREPACK_ENABLE_DOWNLOAD_PROMPT: "0"

run:
  dir: bento
  path: ash
  args:
    - -ce
    - |
      GREEN='\033[0;32m'
      CLEAR='\033[0m'

      corepack enable
      pnpm install
      echo -e "${GREEN}project dependencies installed${CLEAR}"
