platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: "18"

inputs:
  - name: bento

caches:
  - path: bento/.pnpm-store

params:
  CI: true
  NPM_TOKEN: ((npm_token))
  SSH_PRIVATE_KEY: ((private-key))
  GITHUB_TOKEN: ((github-token))

run:
  path: ci/tasks/release.sh
  dir: bento
