platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: "lts-alpine"

inputs:
  - name: bento

params:
  CI: true

run:
  dir: bento
  path: ash
  args:
    - -ce
    - |
      corepack enable
      pnpm test
